### PR TITLE
MMC opti and update to RTEMS 5

### PR DESCRIPTION
**Pull request by sebhub**

### CODE REVIEW

**Comment by eproxus** [comment]
We can't build this branch:

```
$ git submodule update
error: Server does not allow request for unadvertised object 8b5a801e85e273aa9778bbf5b41269ae15fceb30
Fetched in submodule path 'rtems', but it did not contain 8b5a801e85e273aa9778bbf5b41269ae15fceb30. Direct fetching of that commit failed.
```

Seems the `rtems` submodule is still pointing to our old fork at https://github.com/grisp/rtems, which seems outdated.

**Comment by sebhub** [comment]
It should work now.

**Comment by eproxus** [comment]
@sebhub The build now works, thanks!

I'm having trouble running the built Erlang VM using a newly built bootloader. It seems the SD-card cannot be mounted (after the boot loader successfully uses it) and our own call to `grisp_init_wait_for_sd()` fails:

```
----------------
GRISP bootloader
----------------
Version: bootloader-V1.0.1-26-g694f (Build Tue May 15 01:10:22 UTC 2018)
nexus0: <RTEMS Nexus device>
at91_mci0: <MCI mmc/sd host bridge> on nexus0
mmc0: <MMC/SD bus> on at91_mci0
media listener: event = DISK ATTACH, state = INQUIRY, src = mmcsd
media listener: event = DISK ATTACH, state = SUCCESS, src = mmcsd, dest = /dev/mmcsd-0
mmedia listener: event = MOUNT, state = INQUIRY, src = /dev/mmcsd-0
mcsd0: 64GB <SDHC ACLCE 8.0 SN AB062546 MFG 03/2017 by 3 SD> at mmc0 20.5MHz/4bit/1-block
media listener: event = MOUNT, state = FAILED, src = /dev/mmcsd-0
media listener: event = PARTITION INQUIRY, state = INQUIRY, src = /dev/mmcsd-0
media listener: event = PARTITION INQUIRY, state = SUCCESS, src = /dev/mmcsd-0
media listener: event = PARTITION ATTACH, state = INQUIRY, src = /dev/mmcsd-0
media listener: event = PARTITION ATTACH, state = SUCCESS, src = /dev/mmcsd-0, dest = /dev/mmcsd-0-0
media listener: event = MOUNT, state = INQUIRY, src = /dev/mmcsd-0-0
waiting for SD...

media listener: event = MOUNT, state = SUCCESS, src = /dev/mmcsd-0-0, dest = /media/mmcsd-0-0
boot: press key to enter service mode
boot: press key to enter service mode
boot: press key to enter service mode
boot: open file "/media/mmcsd-0-0/robot/erts-9.2/bin/beam.bin"... done
boot: read file "/media/mmcsd-0-0/robot/erts-9.2/bin/beam.bin"... received 5572356 bytes
mounting sd card
nexus0: <RTEMS Nexus device>
if_atsam0 on nexus0
if_atsam0: Ethernet address: 0e:b0:ba:5e:ba:11
_bsd_usb_needs_explore_all: no devclass
ifconfig lo0
waiting for SD...

ERROR: SD could not be mounted after timeout
WARNING: Can't find ini file /media/mmcsd-0-0/grisp.ini -> using defaults
erl.rtems -- -root otp -home home -boot start_sasl -pa .
mkdir /tmp
mkdir /tmp/log
mkdir /home
Setting environment
chdir(/media/mmcsd-0-0/)
can't chdir: No such file or directory

erl_main: starting ...
getcwd: /
hostname: defaulthostname
starting erlang runtime
{"init terminating in do_boot",{'cannot get bootfile','start_sasl.boot'}}
init terminating in do_boot ({cannot get bootfile,start_sasl.boot})

Crash dump is being written to: erl_crash.dump...done
tal extension: source=5, is_internal=0, error=1
```

You can see the initialization we do [here](https://github.com/grisp/grisp/blob/master/grisp/grisp_base/sys/erl_main.c#L277-L285). Any insight into what's wrong would be greatly appreciated!

**Comment by c-mauderer** [comment]
Seems that I forgot to document the necessary changes back when I created the update-to-upstream branch that Sebastian used as a base.

I moved a part of the libbsd-configuration to the libgrisp so that we can integrate everything into the official tree. Please have a look at the changes in bootloader/init.c or sd-sample/init.c in https://github.com/grisp/grisp-software/commit/94a3806d158140aad4a235b92a01a91f5cec31e4#diff-3192913f97a7b25006bd007129a05472L403

**Comment by eproxus** [comment]
@c-mauderer Thanks, that got us off the ground!

Some initial testing results are [here](https://github.com/grisp/grisp/pull/26)...

**Comment by holzingk** [comment]
Compilation of GCC failed for me on Mac OS.

Need to have a closer look what's causing it.

```
kmbp:grisp-software kilian$ tail -n 15 rtems-source-builder/rtems/rsb-report-arm-rtems5-gcc-7.3.0-newlib-3.0.0-x86_64-apple-darwin17.5.0-1.txt
libtool: compile:  /Users/kilian/grisp-software/rtems-source-builder/rtems/build/arm-rtems5-gcc-7.3.0-newlib-3.0.0-x86_64-apple-darwin17.5.0-1/build/./gcc/xgcc -shared-libgcc -B/Users/kilian/grisp-software/rtems-source-builder/rtems/build/arm-rtems5-gcc-7.3.0-newlib-3.0.0-x86_64-apple-darwin17.5.0-1/build/./gcc -nostdinc++ -L/Users/kilian/grisp-software/rtems-source-builder/rtems/build/arm-rtems5-gcc-7.3.0-newlib-3.0.0-x86_64-apple-darwin17.5.0-1/build/arm-rtems5/libstdc++-v3/src -L/Users/kilian/grisp-software/rtems-source-builder/rtems/build/arm-rtems5-gcc-7.3.0-newlib-3.0.0-x86_64-apple-darwin17.5.0-1/build/arm-rtems5/libstdc++-v3/src/.libs -L/Users/kilian/grisp-software/rtems-source-builder/rtems/build/arm-rtems5-gcc-7.3.0-newlib-3.0.0-x86_64-apple-darwin17.5.0-1/build/arm-rtems5/libstdc++-v3/libsupc++/.libs -nostdinc -B/Users/kilian/grisp-software/rtems-source-builder/rtems/build/arm-rtems5-gcc-7.3.0-newlib-3.0.0-x86_64-apple-darwin17.5.0-1/build/arm-rtems5/newlib/ -isystem /Users/kilian/grisp-software/rtems-source-builder/rtems/build/arm-rtems5-gcc-7.3.0-newlib-3.0.0-x86_64-apple-darwin17.5.0-1/build/arm-rtems5/newlib/targ-include -isystem /Users/kilian/grisp-software/rtems-source-builder/rtems/build/arm-rtems5-gcc-7.3.0-newlib-3.0.0-x86_64-apple-darwin17.5.0-1/gcc-7.3.0/newlib/libc/include -B/Users/kilian/grisp-software/rtems-install/rtems/5/arm-rtems5/bin/ -B/Users/kilian/grisp-software/rtems-install/rtems/5/arm-rtems5/lib/ -isystem /Users/kilian/grisp-software/rtems-install/rtems/5/arm-rtems5/include -isystem /Users/kilian/grisp-software/rtems-install/rtems/5/arm-rtems5/sys-include -I/Users/kilian/grisp-software/rtems-source-builder/rtems/build/arm-rtems5-gcc-7.3.0-newlib-3.0.0-x86_64-apple-darwin17.5.0-1/gcc-7.3.0/libstdc++-v3/../libgcc -I/Users/kilian/grisp-software/rtems-source-builder/rtems/build/arm-rtems5-gcc-7.3.0-newlib-3.0.0-x86_64-apple-darwin17.5.0-1/build/arm-rtems5/libstdc++-v3/include/arm-rtems5 -I/Users/kilian/grisp-software/rtems-source-builder/rtems/build/arm-rtems5-gcc-7.3.0-newlib-3.0.0-x86_64-apple-darwin17.5.0-1/build/arm-rtems5/libstdc++-v3/include -I/Users/kilian/grisp-software/rtems-source-builder/rtems/build/arm-rtems5-gcc-7.3.0-newlib-3.0.0-x86_64-apple-darwin17.5.0-1/gcc-7.3.0/libstdc++-v3/libsupc++ -fno-implicit-templates -Wall -Wextra -Wwrite-strings -Wcast-qual -Wabi -fdiagnostics-show-location=once -ffunction-sections -fdata-sections -frandom-seed=bad_array_new.lo -g -O2 -std=gnu++11 -c ../../../../gcc-7.3.0/libstdc++-v3/libsupc++/bad_array_new.cc -o bad_array_new.o
In file included from ../../../../gcc-7.3.0/libstdc++-v3/libsupc++/atexit_thread.cc:24:0:
/Users/kilian/grisp-software/rtems-source-builder/rtems/build/arm-rtems5-gcc-7.3.0-newlib-3.0.0-x86_64-apple-darwin17.5.0-1/gcc-7.3.0/libstdc++-v3/libsupc++/cxxabi.h:52:10: fatal error: bits/cxxabi_init_exception.h: No such file or directory
 #include <bits/cxxabi_init_exception.h>
          ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
compilation terminated.
libtool: compile:  /Users/kilian/grisp-software/rtems-source-builder/rtems/build/arm-rtems5-gcc-7.3.0-newlib-3.0.0-x86_64-apple-darwin17.5.0-1/build/./gcc/xgcc -shared-libgcc -B/Users/kilian/grisp-software/rtems-source-builder/rtems/build/arm-rtems5-gcc-7.3.0-newlib-3.0.0-x86_64-apple-darwin17.5.0-1/build/./gcc -nostdinc++ -L/Users/kilian/grisp-software/rtems-source-builder/rtems/build/arm-rtems5-gcc-7.3.0-newlib-3.0.0-x86_64-apple-darwin17.5.0-1/build/arm-rtems5/libstdc++-v3/src -L/Users/kilian/grisp-software/rtems-source-builder/rtems/build/arm-rtems5-gcc-7.3.0-newlib-3.0.0-x86_64-apple-darwin17.5.0-1/build/arm-rtems5/libstdc++-v3/src/.libs -L/Users/kilian/grisp-software/rtems-source-builder/rtems/build/arm-rtems5-gcc-7.3.0-newlib-3.0.0-x86_64-apple-darwin17.5.0-1/build/arm-rtems5/libstdc++-v3/libsupc++/.libs -nostdinc -B/Users/kilian/grisp-software/rtems-source-builder/rtems/build/arm-rtems5-gcc-7.3.0-newlib-3.0.0-x86_64-apple-darwin17.5.0-1/build/arm-rtems5/newlib/ -isystem /Users/kilian/grisp-software/rtems-source-builder/rtems/build/arm-rtems5-gcc-7.3.0-newlib-3.0.0-x86_64-apple-darwin17.5.0-1/build/arm-rtems5/newlib/targ-include -isystem /Users/kilian/grisp-software/rtems-source-builder/rtems/build/arm-rtems5-gcc-7.3.0-newlib-3.0.0-x86_64-apple-darwin17.5.0-1/gcc-7.3.0/newlib/libc/include -B/Users/kilian/grisp-software/rtems-install/rtems/5/arm-rtems5/bin/ -B/Users/kilian/grisp-software/rtems-install/rtems/5/arm-rtems5/lib/ -isystem /Users/kilian/grisp-software/rtems-install/rtems/5/arm-rtems5/include -isystem /Users/kilian/grisp-software/rtems-install/rtems/5/arm-rtems5/sys-include -I/Users/kilian/grisp-software/rtems-source-builder/rtems/build/arm-rtems5-gcc-7.3.0-newlib-3.0.0-x86_64-apple-darwin17.5.0-1/gcc-7.3.0/libstdc++-v3/../libgcc -I/Users/kilian/grisp-software/rtems-source-builder/rtems/build/arm-rtems5-gcc-7.3.0-newlib-3.0.0-x86_64-apple-darwin17.5.0-1/build/arm-rtems5/libstdc++-v3/include/arm-rtems5 -I/Users/kilian/grisp-software/rtems-source-builder/rtems/build/arm-rtems5-gcc-7.3.0-newlib-3.0.0-x86_64-apple-darwin17.5.0-1/build/arm-rtems5/libstdc++-v3/include -I/Users/kilian/grisp-software/rtems-source-builder/rtems/build/arm-rtems5-gcc-7.3.0-newlib-3.0.0-x86_64-apple-darwin17.5.0-1/gcc-7.3.0/libstdc++-v3/libsupc++ -fno-implicit-templates -Wall -Wextra -Wwrite-strings -Wcast-qual -Wabi -fdiagnostics-show-location=once -ffunction-sections -fdata-sections -frandom-seed=bad_typeid.lo -g -O2 -c ../../../../gcc-7.3.0/libstdc++-v3/libsupc++/bad_typeid.cc -o bad_typeid.o
make[4]: *** [atexit_thread.lo] Error 1
make[4]: *** Waiting for unfinished jobs....
make[3]: *** [all-recursive] Error 1
make[2]: *** [all] Error 2
make[1]: *** [all-target-libstdc++-v3] Error 2
make: *** [all] Error 2
shell cmd failed: /bin/sh -ex  /Users/kilian/grisp-software/rtems-source-builder/rtems/build/arm-rtems5-gcc-7.3.0-newlib-3.0.0-x86_64-apple-darwin17.5.0-1/doit
error: building arm-rtems5-gcc-7.3.0-newlib-3.0.0-x86_64-apple-darwin17.5.0-1

```

**Comment by holzingk** [comment]
Build succeeded now. Had to do with an oudated XCode version.

**Comment by c-mauderer** [comment]
Just noted that you merged this. This should close some other points too. I would assume #3 and #17. Note that for #3 there is also a note in the README that now should be obsolete.

**Pull request merged**
